export const GET_MOVIES = "GET_MOVIES";
export const GET_GENRES = "GET_GENRES";
export const LOADING_MOVIE = "LOADING_MOVIE";
export const UPDATE_TEXT = "UPDATE_TEXT";
export const GET_SEARCHED_MOVIES = "GET_SEARCHED_MOVIES";
export const ZERO_OUT_SEARCH_RESULTS = "ZERO_OUT_SEARCH_RESULTS";
export const GET_MOVIE = "GET_MOVIE";
export const SET_PAGE_PARAMS = "SET_PAGE_PARAMS";