export const GET_MOVIES = "GET_MOVIES";
export const GET_GENRES = "GET_GENRES";
export const LOADING_MOVIES = "LOADING_MOVIES";
export const UPDATE_TEXT = "UPDATE_TEXT";
export const GET_SEARCHED_MOVIES = "GET_SEARCHED_MOVIES";
export const ZERO_OUT_SEARCH_RESULTS = "ZERO_OUT_SEARCH_RESULTS";